name: ContrabandCrate
version: 1.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11]
main: ContrabandCrate\Crate
author: xXCaulDevsYT

commands:
 cratekey:
  description: "§r§d§lmystical crate distribution command"
  permission: "givecratekey.cmd"
  default: false
